Document: libiec61850
Title: Debian libiec61850 Manual
Author: <insert document author here>
Abstract: This manual describes what libiec61850 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libiec61850/libiec61850.sgml.gz

Format: postscript
Files: /usr/share/doc/libiec61850/libiec61850.ps.gz

Format: text
Files: /usr/share/doc/libiec61850/libiec61850.text.gz

Format: HTML
Index: /usr/share/doc/libiec61850/html/index.html
Files: /usr/share/doc/libiec61850/html/*.html
